export const StatesArray = [
  { id: "AZ", description: "Azran" },
  { id: "QL", description: "Quilara" },
  { id: "VX", description: "Vextria" },
  { id: "LT", description: "Lorthan" },
  { id: "NR", description: "Nerophis" },
  { id: "XM", description: "Xyrmox" },
  { id: "PL", description: "Plytheron" },
  { id: "KR", description: "Krelios" },
  { id: "ZH", description: "Zholtan" },
  { id: "CF", description: "Cryfina" },
  { id: "MX", description: "Mixelon" },
  { id: "TH", description: "Thryon" },
  { id: "GD", description: "Glydoria" },
  { id: "YX", description: "Yexium" },
  { id: "BR", description: "Brexaris" },
  { id: "SD", description: "Sildara" },
  { id: "KL", description: "Klendria" },
  { id: "VL", description: "Valtoris" },
  { id: "XY", description: "Xylaria" },
  { id: "JN", description: "Jyntheria" },
  { id: "TR", description: "Troliath" },
  { id: "VX2", description: "Voxenna" }, // Changed id to VX2 to ensure uniqueness
  { id: "RH", description: "Rhythara" },
  { id: "ML", description: "Melithar" },
  { id: "CN", description: "Cyntheron" },
  { id: "LV", description: "Luvithis" },
  { id: "PH", description: "Phorathia" },
  { id: "QR", description: "Qirathas" },
  { id: "WL", description: "Welythos" },
];